### ISSUE TITLE
Tests folder included in fsutil release

### ISSUE THREAD

**Issue by sandre35** [fabiocaccamo/python-fsutil#32]
**Python version**
Python 3.9

**Package version**
Since release 0.9

**Current behavior (bug description)**
In my project, we are using `python-codicefiscale` which has for dependency `python-fsutil`. When launching our Django app, we load our settings located in `tests.[...].settings`. 
Python is taking the fsutil tests folder, located in my virtual environment, as the folder under which my settings are located.
The bug was introduced in this [commit](https://github.com/fabiocaccamo/python-fsutil/commit/e6a61e066e5bdbade8e0c01aae8cb84ae3ffc749). The `tests`folder is not excluded as the wheel is built.

**Expected behavior**
Update the `setup.cfg` file to exclude the `tests` folder.

**Comment by fabiocaccamo** [comment]
@sandre35 thank you for reporting this and for already having investigated it.

**Comment by RemiCardona** [comment]
@fabiocaccamo I tracked down the issue, a PR will appear shortly.

**Comment by fabiocaccamo** [comment]
@sandre35 there was an error in `setup.cfg` [here](https://github.com/fabiocaccamo/python-fsutil/blob/master/setup.cfg#L61), but even fixing it the release contains the `tests/` folder.

**Comment by fabiocaccamo** [comment]
@RemiCardona the dist files are not created locally, but I create the release using with this [workflow](https://github.com/fabiocaccamo/python-fsutil/blob/master/.github/workflows/create-release.yml), I don't think there is persistence.

**Comment by RemiCardona** [comment]
I downloaded the wheel from pypi.org and the tests directory is gone. It all looks fixed to me. Are you looking elsewhere?

**Comment by fabiocaccamo** [comment]
I looked the assets in the [release on GitHub](https://github.com/fabiocaccamo/python-fsutil/releases/tag/0.9.3), tests are still present, but if they are no more on PyPi it's ok.

**Comment by RemiCardona** [comment]
Oh that zipfile is created by github on the fly, it's just an archive of the files in the git repo under the tag. It's fine to ignore that!
Thanks for the quick release, it's very much appreciated :pray:
