### ISSUE TITLE
File permissions get lost when using write_file with atomic=True

### ISSUE THREAD

**Issue by cmile** [fabiocaccamo/python-fsutil#94]
**Python version**
3.9

**Package version**
0.12.0

**Current behavior (bug description)**
When writing files using `write_file` with `atomic=True`, the file permissions of the original file get lost and are always set to `600`.

**Expected behavior**
The file permissions of the file that is written to should be kept as is, no matter if you use atomic write or not.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/python-fsutil/issues/94">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-fsutil/issues/94/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-fsutil/issues/94/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@cmile thank you for reporting this issue.

**Comment by cmile** [comment]
@fabiocaccamo  I have proposed a solution, but I'm struggling with an appropriate test for this.

**Comment by cmile** [comment]
Sorry, after some more testing it turns out that my PR does not solve the issue :(

**Comment by fabiocaccamo** [comment]
@cmile I took this opportunity to add `get_permissions` and `set_permissions` methods.

**Comment by fabiocaccamo** [comment]
@cmile fixed in `0.13.0` version.
